name: Build and Publish Website

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Website

    env:
      COMMIT_SECRET: ${{secrets.commit_secret}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2
    - uses: subosito/flutter-action@v2.14.0
    - run: flutter pub get
    - run: flutter build web --release --base-href /quiverware-website/
    - run: |
        cp CNAME build/web/CNAME
        cd build/web
        git init
        git config --global user.email mjordan@quiverware.com
        git config --global user.name mjordan
        git status
        git remote add origin https://${{secrets.commit_secret}}@github.com/quiverware/quiverware-website.git
        git checkout -b main
        git add --all
        git commit -m "update website"
        git push origin main -f
